### ISSUE TITLE
Script updates

### ISSUE THREAD

**Issue by cball** [echobind/react-native-template-echobind#3]
- Use --skip-packager for storybook script
- add `testID` to intro screen so detox tests pass
- Fix app name in storybook.js
- Yarn install with latest yarn

**Comment by gprocell927** [comment]
@cball : The `testID` I can get in. However, when trying to fix the app name in storybook.js. I can't seem to get the app name to import from `app.json` correctly. 

I'm currently trying 
```AppRegistry.registerComponent(appName, () => StorybookUIHMRRoot);``` while importing `{name as appName} from '../app.json'`. The name in that file is what I've named the app, but it doesn't seem to transfer over. Is there a possibility that this value is set somewhere else in the timeline of generating the app?

**Comment by cball** [comment]
Looks like this was fixed. Skip-packager is irrelevant now due to #11
