### ISSUE TITLE
RFC: change repo name to react-native-template

### ISSUE THREAD

**Issue by jsjoeio** [echobind/react-native-template-echobind#72]
I'm sure there's a good reason behind it but I'm thinking since this repo belongs to the "echobind" GitHub org, we could remove the company name in the repo name.

In addition, I'm hoping when we publish to npm, we can call this:
`@echobind/react-native-template`

**Comment by jsjoeio** [comment]
@cball @rynatk @isaiahgrey93 thoughts?

**Comment by cball** [comment]
If this weren't being leveraged by the cli I'd totally agree. If the package is prefixed with `react-native-template-<whatever>` then the cli will pick it up and you should be able to install it automagically via `react-native init --template=echobind`

**Comment by cball** [comment]
Actually this may have changed since we last looked at it. Give your comment in https://github.com/echobind/react-native-template-echobind/issues/59, you're saying it's possible to provide any package as an argument?

**Comment by jsjoeio** [comment]
I believe so. That screenshot was taken from the [docs here](https://github.com/react-native-community/cli/blob/master/docs/commands.md#init)

**Comment by cball** [comment]
I'm 👍 with it. Upon reading that it actually looks like we may be able to replace some of the things we were doing manually as well:


```js
// template.config.js
module.exports = {
  placeholderName: 'ProjectName',
  titlePlaceholder: 'Project Display Name',
  templateDir: './template',
  postInitScript: './script.js',
};
```

**Comment by jsjoeio** [comment]
Oh nice! I'll make that a separate issue

**Comment by jsjoeio** [comment]
Going to rename the repository to `react-native-template`

Then, I'll publish it to npm as part of #59
